#! /bin/bash
    srv_name="${serv_names[${indx}]}"
    script_name="${script_names[${indx}]}"
    starter_filename="${tmp_dir}/${srv_name}"
    log_filename="${logs_dir}/${srv_name}.log"
    pid_filename="${tmp_dir}/PID.txt"

    make_starter_file "${srv_name}" "${root_dir}/${serv_pathes[${indx}]}" "${log_filename}" "${tfly_starter_dir}" "${add_options[${indx}]}" "${home_dir}" "${starter_filename}" "${conf_dir}/${java_versions[${indx}]}" "${grails_versions[${indx}]}"
    launch_service_tmux "${starter_filename}" "${log_filename}" "${srv_name}" "${pid_filename}" 
    srv_pid=`cat "${pid_filename}"`

